import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import {
  maskSensitiveValues,
  sanitizeForLogging,
  createLogger,
} from '../src/utils/sanitize';

/**
 * Property 17: Log Sanitization
 * **Validates: Requirements 8.5**
 * 
 * *For any* log entry generated by the Worker, the entry SHALL NOT contain:
 * - API keys in plain text
 * - Authentication tokens
 * - Full upstream credentials
 */
describe('Property 17: Log Sanitization', () => {
  // Generator for API keys (32+ character alphanumeric strings)
  const apiKeyArb = fc.stringOf(
    fc.constantFrom(...'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-'),
    { minLength: 32, maxLength: 64 }
  );

  // Generator for Bearer tokens
  const bearerTokenArb = fc.tuple(
    fc.constant('Bearer '),
    fc.stringOf(
      fc.constantFrom(...'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._-'),
      { minLength: 20, maxLength: 100 }
    )
  ).map(([prefix, token]) => `${prefix}${token}`);

  // Generator for key=value credential patterns
  const credentialPatternArb = fc.tuple(
    fc.constantFrom('api_key', 'apiKey', 'api-key', 'token', 'secret', 'password', 'authorization', 'credential'),
    fc.constantFrom('=', ': '),
    fc.stringOf(
      fc.constantFrom(...'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'),
      { minLength: 16, maxLength: 64 }
    )
  ).map(([key, sep, value]) => `${key}${sep}${value}`);

  // Generator for X-API-Key header values
  const xApiKeyHeaderArb = fc.tuple(
    fc.constant('X-API-Key'),
    fc.constantFrom('=', ': '),
    fc.stringOf(
      fc.constantFrom(...'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'),
      { minLength: 32, maxLength: 64 }
    )
  ).map(([header, sep, value]) => `${header}${sep}${value}`);

  describe('API Key Masking', () => {
    it('should mask long alphanumeric strings (potential API keys)', () => {
      fc.assert(
        fc.property(apiKeyArb, (apiKey) => {
          const logMessage = `Request with key: ${apiKey}`;
          const sanitized = maskSensitiveValues(logMessage);
          
          // The full API key should not appear in the sanitized output
          expect(sanitized).not.toContain(apiKey);
          // Should contain masked pattern (first 4 chars + **** + last 4 chars)
          expect(sanitized).toContain('****');
        }),
        { numRuns: 100 }
      );
    });

    it('should preserve first and last 4 characters when masking long keys', () => {
      fc.assert(
        fc.property(apiKeyArb, (apiKey) => {
          const sanitized = maskSensitiveValues(apiKey);
          
          // Should start with first 4 chars of original
          expect(sanitized.startsWith(apiKey.substring(0, 4))).toBe(true);
          // Should end with last 4 chars of original
          expect(sanitized.endsWith(apiKey.substring(apiKey.length - 4))).toBe(true);
          // Should contain mask in the middle
          expect(sanitized).toContain('****');
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('Bearer Token Masking', () => {
    it('should mask Bearer tokens completely', () => {
      fc.assert(
        fc.property(bearerTokenArb, (bearerToken) => {
          const logMessage = `Authorization header: ${bearerToken}`;
          const sanitized = maskSensitiveValues(logMessage);
          
          // Should replace the token with ****
          expect(sanitized).toContain('Bearer ****');
          // The original token value should not appear
          const tokenValue = bearerToken.replace('Bearer ', '');
          expect(sanitized).not.toContain(tokenValue);
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('Credential Pattern Masking', () => {
    it('should mask key=value credential patterns', () => {
      fc.assert(
        fc.property(credentialPatternArb, (credential) => {
          const logMessage = `Config: ${credential}`;
          const sanitized = maskSensitiveValues(logMessage);
          
          // Should contain the key but mask the value
          expect(sanitized).toContain('****');
          // The original credential value should not appear in full
          const parts = credential.split(/[=:]\s*/);
          if (parts.length > 1 && parts[1].length > 8) {
            expect(sanitized).not.toContain(parts[1]);
          }
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('X-API-Key Header Masking', () => {
    it('should mask X-API-Key header values', () => {
      fc.assert(
        fc.property(xApiKeyHeaderArb, (header) => {
          const logMessage = `Headers: ${header}`;
          const sanitized = maskSensitiveValues(logMessage);
          
          // Should mask the API key value
          expect(sanitized).toContain('X-API-Key=****');
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('Object Sanitization for Logging', () => {
    // Generator for objects with sensitive keys
    const sensitiveObjectArb = fc.record({
      apiKey: apiKeyArb,
      token: fc.stringOf(
        fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz0123456789'),
        { minLength: 20, maxLength: 40 }
      ),
      secret: fc.stringOf(
        fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz0123456789'),
        { minLength: 16, maxLength: 32 }
      ),
      password: fc.stringOf(
        fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz0123456789!@#$'),
        { minLength: 8, maxLength: 20 }
      ),
      authorization: fc.stringOf(
        fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz0123456789'),
        { minLength: 20, maxLength: 50 }
      ),
      // Non-sensitive field
      username: fc.stringOf(
        fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz'),
        { minLength: 3, maxLength: 15 }
      ),
    });

    it('should mask sensitive keys in objects', () => {
      fc.assert(
        fc.property(sensitiveObjectArb, (obj) => {
          const sanitized = sanitizeForLogging(obj) as Record<string, string>;
          
          // Sensitive keys should be masked
          expect(sanitized.apiKey).toContain('****');
          expect(sanitized.token).toContain('****');
          expect(sanitized.secret).toContain('****');
          expect(sanitized.password).toContain('****');
          expect(sanitized.authorization).toContain('****');
          
          // Original values should not appear in full
          expect(sanitized.apiKey).not.toBe(obj.apiKey);
          expect(sanitized.token).not.toBe(obj.token);
          expect(sanitized.secret).not.toBe(obj.secret);
          expect(sanitized.password).not.toBe(obj.password);
          expect(sanitized.authorization).not.toBe(obj.authorization);
        }),
        { numRuns: 100 }
      );
    });

    it('should preserve non-sensitive fields', () => {
      fc.assert(
        fc.property(
          fc.record({
            name: fc.string({ minLength: 1, maxLength: 20 }),
            count: fc.nat({ max: 1000 }),
            enabled: fc.boolean(),
          }),
          (obj) => {
            const sanitized = sanitizeForLogging(obj) as typeof obj;
            
            // Non-sensitive fields should be preserved
            expect(sanitized.name).toBe(obj.name);
            expect(sanitized.count).toBe(obj.count);
            expect(sanitized.enabled).toBe(obj.enabled);
          }
        ),
        { numRuns: 100 }
      );
    });
  });

  describe('Nested Object Sanitization', () => {
    it('should recursively sanitize nested objects', () => {
      fc.assert(
        fc.property(
          fc.record({
            user: fc.record({
              name: fc.string({ minLength: 1, maxLength: 20 }),
              credentials: fc.record({
                apiKey: apiKeyArb,
                token: fc.stringOf(
                  fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz0123456789'),
                  { minLength: 20, maxLength: 40 }
                ),
              }),
            }),
          }),
          (obj) => {
            const sanitized = sanitizeForLogging(obj) as {
              user: {
                name: string;
                credentials: { apiKey: string; token: string };
              };
            };
            
            // Nested sensitive fields should be masked
            expect(sanitized.user.credentials.apiKey).toContain('****');
            expect(sanitized.user.credentials.token).toContain('****');
            // Non-sensitive nested fields should be preserved
            expect(sanitized.user.name).toBe(obj.user.name);
          }
        ),
        { numRuns: 100 }
      );
    });
  });

  describe('Array Sanitization', () => {
    it('should sanitize arrays containing sensitive data', () => {
      fc.assert(
        fc.property(
          fc.array(apiKeyArb, { minLength: 1, maxLength: 5 }),
          (keys) => {
            const sanitized = sanitizeForLogging(keys) as string[];
            
            // Each key should be masked
            for (let i = 0; i < keys.length; i++) {
              expect(sanitized[i]).toContain('****');
              expect(sanitized[i]).not.toBe(keys[i]);
            }
          }
        ),
        { numRuns: 100 }
      );
    });
  });

  describe('SanitizedLogger', () => {
    it('should create a logger that masks sensitive values', () => {
      const logger = createLogger('[Test] ');
      
      // Logger should be created successfully
      expect(logger).toBeDefined();
      expect(typeof logger.info).toBe('function');
      expect(typeof logger.warn).toBe('function');
      expect(typeof logger.error).toBe('function');
      expect(typeof logger.debug).toBe('function');
    });
  });

  describe('Edge Cases', () => {
    it('should handle null and undefined values', () => {
      expect(sanitizeForLogging(null)).toBeNull();
      expect(sanitizeForLogging(undefined)).toBeUndefined();
    });

    it('should handle primitive values', () => {
      fc.assert(
        fc.property(fc.nat(), (num) => {
          expect(sanitizeForLogging(num)).toBe(num);
        }),
        { numRuns: 50 }
      );

      fc.assert(
        fc.property(fc.boolean(), (bool) => {
          expect(sanitizeForLogging(bool)).toBe(bool);
        }),
        { numRuns: 10 }
      );
    });

    it('should handle empty strings', () => {
      expect(maskSensitiveValues('')).toBe('');
    });

    it('should handle strings shorter than mask threshold', () => {
      const shortString = 'abc';
      const sanitized = maskSensitiveValues(shortString);
      // Short strings without sensitive patterns should pass through
      expect(sanitized).toBe(shortString);
    });
  });
});
